### PR TITLE
Several fixes necessary for merging.

### PR DESCRIPTION
**Pull request by dannon**
Ran grunt to create two missing files, fixed static path that was broken in one of the templates.
Also updated against hte latest -dev.
Fixed static paths broken in the .less, rebuilt CSS.

### CODE REVIEW

**Comment by dannon** [comment]
Argh.  I incorrectly targeted this to your dev branch and not reports homepage :/\

Can you merge this over, or would you like for me to reissue the PR?  (Should just be git checkout Reports_homepage; git pull dev)

**Comment by Airistotal** [comment]
Yeah, I'm moving it now so no need for a PR. I realized that after I merged, derr.

**Comment by dannon** [comment]
Sounds good.  I'm working on another followup fix to D3 usage as well, but will issue a separate correct PR for that.

**Comment by Airistotal** [comment]
:) Sounds good.

**Pull request merged**
